[package]
name = "storage-service"
edition = "2024"
version.workspace = true
authors.workspace = true
license.workspace = true
rust-version.workspace = true
repository.workspace = true

[dependencies]
# Internal
file-system = { path = "../file-system", default-features = false, features = ["sync"] }
storage-model = { path = "../storage-model", default-features = false, features = ["std"] }

[dev-dependencies]
# Internal
file-system = { path = "../file-system", default-features = false, features = ["in-memory"] }

# Async
tokio = { version = "1.52", default-features = false, features = [
  "rt",
  "macros",
] }
