[package]
name = "storage-service"
edition = "2024"
version.workspace = true
authors.workspace = true
license.workspace = true
rust-version.workspace = true
repository.workspace = true

[dependencies]
# Internal
file-system = { path = "../file-system", default-features = false, features = [] }
idp-model = { path = "../idp-model", default-features = false, features = ["std"] }
storage-model = { path = "../storage-model", default-features = false, features = ["std"] }

# Serialization
serde = { version = "1.0", default-features = false, features = ["derive", "std"] }
serde_json = { version = "1.0", default-features = false, features = ["std"] }

# Async
tokio = { version = "1.53", default-features = false, features = ["sync"] }

[dev-dependencies]
# Async
tokio = { version = "1.52", default-features = false, features = [
  "rt",
  "macros",
] }
