[package]
name = "bootstrap-service"
version = "0.1.0"
publish = false
authors.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true
description = "Identity control-plane bootstrap service"

[lib]
name = "bootstrap_service"

[features]
default = ["std"]
std = ["idp-model/std", "idp-service/std", "management-service/std"]

[dependencies]
# Internal
idp-model = { path = "../idp-model", default-features = false, features = [] }
idp-service = { path = "../idp-service", default-features = false, features = [] }
management-service = { path = "../management-service", default-features = false, features = [] }

# Error Handling
thiserror = { version = "2.0", default-features = false, features = [] }

# Serialization
serde = { version = "1.0", default-features = false, features = ["derive"] }

# Logging
log = { version = "0.4", default-features = false, features = [] }
