/* tslint:disable */
/* eslint-disable */
/**
 * LIDP Management API
 * Management API server for LIDP
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../runtime.js";
import type { EntityType } from "./EntityType.js";
import {
    EntityTypeFromJSON,
    EntityTypeFromJSONTyped,
    EntityTypeToJSON,
    EntityTypeToJSONTyped,
} from "./EntityType.js";

/**
 *
 * @export
 * @interface ManagementKey
 */
export interface ManagementKey {
    /**
     *
     */
    createdAt: number;
    /**
     *
     */
    derivationPath: string;
    /**
     *
     */
    entityId: number;
    /**
     *
     */
    entityType: EntityType;
    /**
     *
     */
    expiresAt?: number | null;
    /**
     *
     */
    hardened: boolean;
    /**
     *
     */
    id: number;
    /**
     *
     */
    name: string;
    /**
     *
     */
    parentId?: number | null;
    /**
     *
     */
    revokedAt?: number | null;
    /**
     *
     */
    updatedAt: number;
}

/**
 * Check if a given object implements the ManagementKey interface.
 */
export function instanceOfManagementKey(value: object): value is ManagementKey {
    if (
        (!("createdAt" in (value as Record<string, any>)) &&
            !("created_at" in (value as Record<string, any>))) ||
        ((value as Record<string, any>)["createdAt"] === undefined &&
            (value as Record<string, any>)["created_at"] === undefined)
    )
        return false;
    if (
        (!("derivationPath" in (value as Record<string, any>)) &&
            !("derivation_path" in (value as Record<string, any>))) ||
        ((value as Record<string, any>)["derivationPath"] === undefined &&
            (value as Record<string, any>)["derivation_path"] === undefined)
    )
        return false;
    if (
        (!("entityId" in (value as Record<string, any>)) &&
            !("entity_id" in (value as Record<string, any>))) ||
        ((value as Record<string, any>)["entityId"] === undefined &&
            (value as Record<string, any>)["entity_id"] === undefined)
    )
        return false;
    if (
        (!("entityType" in (value as Record<string, any>)) &&
            !("entity_type" in (value as Record<string, any>))) ||
        ((value as Record<string, any>)["entityType"] === undefined &&
            (value as Record<string, any>)["entity_type"] === undefined)
    )
        return false;
    if (!("hardened" in value) || value["hardened"] === undefined) return false;
    if (!("id" in value) || value["id"] === undefined) return false;
    if (!("name" in value) || value["name"] === undefined) return false;
    if (
        (!("updatedAt" in (value as Record<string, any>)) &&
            !("updated_at" in (value as Record<string, any>))) ||
        ((value as Record<string, any>)["updatedAt"] === undefined &&
            (value as Record<string, any>)["updated_at"] === undefined)
    )
        return false;
    return true;
}

export function ManagementKeyFromJSON(json: any): ManagementKey {
    return ManagementKeyFromJSONTyped(json, false);
}

export function ManagementKeyFromJSONTyped(
    json: any,
    ignoreDiscriminator: boolean,
): ManagementKey {
    if (json == null) {
        return json;
    }
    return {
        createdAt: json["created_at"],
        derivationPath: json["derivation_path"],
        entityId: json["entity_id"],
        entityType: EntityTypeFromJSON(json["entity_type"]),
        expiresAt:
            json["expires_at"] === undefined
                ? undefined
                : json["expires_at"] === null
                  ? null
                  : json["expires_at"],
        hardened: json["hardened"],
        id: json["id"],
        name: json["name"],
        parentId:
            json["parent_id"] === undefined
                ? undefined
                : json["parent_id"] === null
                  ? null
                  : json["parent_id"],
        revokedAt:
            json["revoked_at"] === undefined
                ? undefined
                : json["revoked_at"] === null
                  ? null
                  : json["revoked_at"],
        updatedAt: json["updated_at"],
    };
}

export function ManagementKeyToJSON(json: any): ManagementKey {
    return ManagementKeyToJSONTyped(json, false);
}

export function ManagementKeyToJSONTyped(
    value?: ManagementKey | null,
    ignoreDiscriminator: boolean = false,
): any {
    if (value == null) {
        return value;
    }

    return {
        created_at: value["createdAt"],
        derivation_path: value["derivationPath"],
        entity_id: value["entityId"],
        entity_type: EntityTypeToJSON(value["entityType"]),
        expires_at: value["expiresAt"],
        hardened: value["hardened"],
        id: value["id"],
        name: value["name"],
        parent_id: value["parentId"],
        revoked_at: value["revokedAt"],
        updated_at: value["updatedAt"],
    };
}
