/* tslint:disable */
/* eslint-disable */
/**
 * LIDP Management API
 * Management API server for LIDP
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../runtime.js";
/**
 *
 * @export
 * @interface UpdateApplicationRequest
 */
export interface UpdateApplicationRequest {
    /**
     *
     */
    description?: string | null;
    /**
     *
     */
    name?: string | null;
    /**
     *
     */
    uri?: string | null;
}

/**
 * Check if a given object implements the UpdateApplicationRequest interface.
 */
export function instanceOfUpdateApplicationRequest(
    value: object,
): value is UpdateApplicationRequest {
    return true;
}

export function UpdateApplicationRequestFromJSON(
    json: any,
): UpdateApplicationRequest {
    return UpdateApplicationRequestFromJSONTyped(json, false);
}

export function UpdateApplicationRequestFromJSONTyped(
    json: any,
    ignoreDiscriminator: boolean,
): UpdateApplicationRequest {
    if (json == null) {
        return json;
    }
    return {
        description:
            json["description"] === undefined
                ? undefined
                : json["description"] === null
                  ? null
                  : json["description"],
        name:
            json["name"] === undefined
                ? undefined
                : json["name"] === null
                  ? null
                  : json["name"],
        uri:
            json["uri"] === undefined
                ? undefined
                : json["uri"] === null
                  ? null
                  : json["uri"],
    };
}

export function UpdateApplicationRequestToJSON(
    json: any,
): UpdateApplicationRequest {
    return UpdateApplicationRequestToJSONTyped(json, false);
}

export function UpdateApplicationRequestToJSONTyped(
    value?: UpdateApplicationRequest | null,
    ignoreDiscriminator: boolean = false,
): any {
    if (value == null) {
        return value;
    }

    return {
        description: value["description"],
        name: value["name"],
        uri: value["uri"],
    };
}
