[package]
name = "idp-db"
version = "0.1.0"
publish = false
authors.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true
description = "OAuth 2.x database utilities"

[lib]
name = "db"

[features]
default = ["native", "replica"]
native = ["dep:converge", "converge/automerge", "converge/redb"]
replica = ["native", "converge/in-memory", "converge/macros"]

[dependencies]
# Database
converge = { path = "../../../db", default-features = false, features = ["sql"], optional = true }
