/* tslint:disable */
/* eslint-disable */
/**
 * LIDP Management API
 * Management API server for LIDP
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../runtime.js";
/**
 *
 * @export
 * @interface ApplicationRegistration
 */
export interface ApplicationRegistration {
    /**
     *
     */
    description?: string | null;
    /**
     *
     */
    name?: string | null;
    /**
     *
     */
    uri: string;
}

/**
 * Check if a given object implements the ApplicationRegistration interface.
 */
export function instanceOfApplicationRegistration(
    value: object,
): value is ApplicationRegistration {
    if (!("uri" in value) || value["uri"] === undefined) return false;
    return true;
}

export function ApplicationRegistrationFromJSON(
    json: any,
): ApplicationRegistration {
    return ApplicationRegistrationFromJSONTyped(json, false);
}

export function ApplicationRegistrationFromJSONTyped(
    json: any,
    ignoreDiscriminator: boolean,
): ApplicationRegistration {
    if (json == null) {
        return json;
    }
    return {
        description:
            json["description"] === undefined
                ? undefined
                : json["description"] === null
                  ? null
                  : json["description"],
        name:
            json["name"] === undefined
                ? undefined
                : json["name"] === null
                  ? null
                  : json["name"],
        uri: json["uri"],
    };
}

export function ApplicationRegistrationToJSON(
    json: any,
): ApplicationRegistration {
    return ApplicationRegistrationToJSONTyped(json, false);
}

export function ApplicationRegistrationToJSONTyped(
    value?: ApplicationRegistration | null,
    ignoreDiscriminator: boolean = false,
): any {
    if (value == null) {
        return value;
    }

    return {
        description: value["description"],
        name: value["name"],
        uri: value["uri"],
    };
}
