/* tslint:disable */
/* eslint-disable */
/**
 * LIDP Management API
 * Management API server for LIDP
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../runtime.js";
/**
 *
 * @export
 * @interface UserConsentResponse
 */
export interface UserConsentResponse {
    /**
     *
     */
    clientId: string;
    /**
     *
     */
    createdAt: number;
    /**
     *
     */
    id: number;
    /**
     *
     */
    redirectUri: string;
    /**
     *
     */
    scope: string;
    /**
     *
     */
    updatedAt: number;
    /**
     *
     */
    userId: number;
}

/**
 * Check if a given object implements the UserConsentResponse interface.
 */
export function instanceOfUserConsentResponse(
    value: object,
): value is UserConsentResponse {
    if (
        (!("clientId" in (value as Record<string, any>)) &&
            !("client_id" in (value as Record<string, any>))) ||
        ((value as Record<string, any>)["clientId"] === undefined &&
            (value as Record<string, any>)["client_id"] === undefined)
    )
        return false;
    if (
        (!("createdAt" in (value as Record<string, any>)) &&
            !("created_at" in (value as Record<string, any>))) ||
        ((value as Record<string, any>)["createdAt"] === undefined &&
            (value as Record<string, any>)["created_at"] === undefined)
    )
        return false;
    if (!("id" in value) || value["id"] === undefined) return false;
    if (
        (!("redirectUri" in (value as Record<string, any>)) &&
            !("redirect_uri" in (value as Record<string, any>))) ||
        ((value as Record<string, any>)["redirectUri"] === undefined &&
            (value as Record<string, any>)["redirect_uri"] === undefined)
    )
        return false;
    if (!("scope" in value) || value["scope"] === undefined) return false;
    if (
        (!("updatedAt" in (value as Record<string, any>)) &&
            !("updated_at" in (value as Record<string, any>))) ||
        ((value as Record<string, any>)["updatedAt"] === undefined &&
            (value as Record<string, any>)["updated_at"] === undefined)
    )
        return false;
    if (
        (!("userId" in (value as Record<string, any>)) &&
            !("user_id" in (value as Record<string, any>))) ||
        ((value as Record<string, any>)["userId"] === undefined &&
            (value as Record<string, any>)["user_id"] === undefined)
    )
        return false;
    return true;
}

export function UserConsentResponseFromJSON(json: any): UserConsentResponse {
    return UserConsentResponseFromJSONTyped(json, false);
}

export function UserConsentResponseFromJSONTyped(
    json: any,
    ignoreDiscriminator: boolean,
): UserConsentResponse {
    if (json == null) {
        return json;
    }
    return {
        clientId: json["client_id"],
        createdAt: json["created_at"],
        id: json["id"],
        redirectUri: json["redirect_uri"],
        scope: json["scope"],
        updatedAt: json["updated_at"],
        userId: json["user_id"],
    };
}

export function UserConsentResponseToJSON(json: any): UserConsentResponse {
    return UserConsentResponseToJSONTyped(json, false);
}

export function UserConsentResponseToJSONTyped(
    value?: UserConsentResponse | null,
    ignoreDiscriminator: boolean = false,
): any {
    if (value == null) {
        return value;
    }

    return {
        client_id: value["clientId"],
        created_at: value["createdAt"],
        id: value["id"],
        redirect_uri: value["redirectUri"],
        scope: value["scope"],
        updated_at: value["updatedAt"],
        user_id: value["userId"],
    };
}
