/* tslint:disable */
/* eslint-disable */
/**
 * OAuth Server
 * OIDC / OAuth 2.x server implementation
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../runtime.js";
/**
 *
 * @export
 * @interface DeviceEnrollmentRequest
 */
export interface DeviceEnrollmentRequest {
    /**
     *
     */
    address: string;
    /**
     *
     */
    name: string;
    /**
     *
     */
    publicKey: string;
}

/**
 * Check if a given object implements the DeviceEnrollmentRequest interface.
 */
export function instanceOfDeviceEnrollmentRequest(
    value: object,
): value is DeviceEnrollmentRequest {
    if (!("address" in value) || value["address"] === undefined) return false;
    if (!("name" in value) || value["name"] === undefined) return false;
    if (!("publicKey" in value) || value["publicKey"] === undefined)
        return false;
    return true;
}

export function DeviceEnrollmentRequestFromJSON(
    json: any,
): DeviceEnrollmentRequest {
    return DeviceEnrollmentRequestFromJSONTyped(json, false);
}

export function DeviceEnrollmentRequestFromJSONTyped(
    json: any,
    ignoreDiscriminator: boolean,
): DeviceEnrollmentRequest {
    if (json == null) {
        return json;
    }
    return {
        address: json["address"],
        name: json["name"],
        publicKey: json["publicKey"],
    };
}

export function DeviceEnrollmentRequestToJSON(
    json: any,
): DeviceEnrollmentRequest {
    return DeviceEnrollmentRequestToJSONTyped(json, false);
}

export function DeviceEnrollmentRequestToJSONTyped(
    value?: DeviceEnrollmentRequest | null,
    ignoreDiscriminator: boolean = false,
): any {
    if (value == null) {
        return value;
    }

    return {
        address: value["address"],
        name: value["name"],
        publicKey: value["publicKey"],
    };
}
