/* tslint:disable */
/* eslint-disable */
/**
 * OAuth Server
 * OIDC / OAuth 2.x server implementation
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../runtime.js";
/**
 *
 * @export
 * @interface TunnelAuthorizationRequest
 */
export interface TunnelAuthorizationRequest {
    /**
     *
     */
    localPublicKey: string;
    /**
     *
     */
    remotePublicKey: string;
    /**
     *
     */
    vaultIdHash: string;
}

/**
 * Check if a given object implements the TunnelAuthorizationRequest interface.
 */
export function instanceOfTunnelAuthorizationRequest(
    value: object,
): value is TunnelAuthorizationRequest {
    if (!("localPublicKey" in value) || value["localPublicKey"] === undefined)
        return false;
    if (!("remotePublicKey" in value) || value["remotePublicKey"] === undefined)
        return false;
    if (!("vaultIdHash" in value) || value["vaultIdHash"] === undefined)
        return false;
    return true;
}

export function TunnelAuthorizationRequestFromJSON(
    json: any,
): TunnelAuthorizationRequest {
    return TunnelAuthorizationRequestFromJSONTyped(json, false);
}

export function TunnelAuthorizationRequestFromJSONTyped(
    json: any,
    ignoreDiscriminator: boolean,
): TunnelAuthorizationRequest {
    if (json == null) {
        return json;
    }
    return {
        localPublicKey: json["localPublicKey"],
        remotePublicKey: json["remotePublicKey"],
        vaultIdHash: json["vaultIdHash"],
    };
}

export function TunnelAuthorizationRequestToJSON(
    json: any,
): TunnelAuthorizationRequest {
    return TunnelAuthorizationRequestToJSONTyped(json, false);
}

export function TunnelAuthorizationRequestToJSONTyped(
    value?: TunnelAuthorizationRequest | null,
    ignoreDiscriminator: boolean = false,
): any {
    if (value == null) {
        return value;
    }

    return {
        localPublicKey: value["localPublicKey"],
        remotePublicKey: value["remotePublicKey"],
        vaultIdHash: value["vaultIdHash"],
    };
}
