/* tslint:disable */
/* eslint-disable */
/**
 * OAuth Server
 * OIDC / OAuth 2.x server implementation
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../runtime.js";
/**
 *
 * @export
 * @interface DevicePairingRequest
 */
export interface DevicePairingRequest {
    /**
     *
     */
    acceptingPublicKey: string;
    /**
     *
     */
    address: string;
    /**
     *
     */
    name: string;
    /**
     *
     */
    publicKey: string;
}

/**
 * Check if a given object implements the DevicePairingRequest interface.
 */
export function instanceOfDevicePairingRequest(
    value: object,
): value is DevicePairingRequest {
    if (
        !("acceptingPublicKey" in value) ||
        value["acceptingPublicKey"] === undefined
    )
        return false;
    if (!("address" in value) || value["address"] === undefined) return false;
    if (!("name" in value) || value["name"] === undefined) return false;
    if (!("publicKey" in value) || value["publicKey"] === undefined)
        return false;
    return true;
}

export function DevicePairingRequestFromJSON(json: any): DevicePairingRequest {
    return DevicePairingRequestFromJSONTyped(json, false);
}

export function DevicePairingRequestFromJSONTyped(
    json: any,
    ignoreDiscriminator: boolean,
): DevicePairingRequest {
    if (json == null) {
        return json;
    }
    return {
        acceptingPublicKey: json["acceptingPublicKey"],
        address: json["address"],
        name: json["name"],
        publicKey: json["publicKey"],
    };
}

export function DevicePairingRequestToJSON(json: any): DevicePairingRequest {
    return DevicePairingRequestToJSONTyped(json, false);
}

export function DevicePairingRequestToJSONTyped(
    value?: DevicePairingRequest | null,
    ignoreDiscriminator: boolean = false,
): any {
    if (value == null) {
        return value;
    }

    return {
        acceptingPublicKey: value["acceptingPublicKey"],
        address: value["address"],
        name: value["name"],
        publicKey: value["publicKey"],
    };
}
