/* tslint:disable */
/* eslint-disable */
/**
 * OAuth Server
 * OIDC / OAuth 2.x server implementation
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../runtime.js";
/**
 *
 * @export
 * @interface DevicePairingApprovalPayload
 */
export interface DevicePairingApprovalPayload {
    /**
     *
     */
    payload: string;
}

/**
 * Check if a given object implements the DevicePairingApprovalPayload interface.
 */
export function instanceOfDevicePairingApprovalPayload(
    value: object,
): value is DevicePairingApprovalPayload {
    if (!("payload" in value) || value["payload"] === undefined) return false;
    return true;
}

export function DevicePairingApprovalPayloadFromJSON(
    json: any,
): DevicePairingApprovalPayload {
    return DevicePairingApprovalPayloadFromJSONTyped(json, false);
}

export function DevicePairingApprovalPayloadFromJSONTyped(
    json: any,
    ignoreDiscriminator: boolean,
): DevicePairingApprovalPayload {
    if (json == null) {
        return json;
    }
    return {
        payload: json["payload"],
    };
}

export function DevicePairingApprovalPayloadToJSON(
    json: any,
): DevicePairingApprovalPayload {
    return DevicePairingApprovalPayloadToJSONTyped(json, false);
}

export function DevicePairingApprovalPayloadToJSONTyped(
    value?: DevicePairingApprovalPayload | null,
    ignoreDiscriminator: boolean = false,
): any {
    if (value == null) {
        return value;
    }

    return {
        payload: value["payload"],
    };
}
