/* tslint:disable */
/* eslint-disable */
/**
 * OAuth Server
 * OIDC / OAuth 2.x server implementation
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../runtime.js";
/**
 *
 * @export
 * @interface DeviceSignature
 */
export interface DeviceSignature {
    /**
     *
     */
    signature: string;
}

/**
 * Check if a given object implements the DeviceSignature interface.
 */
export function instanceOfDeviceSignature(
    value: object,
): value is DeviceSignature {
    if (!("signature" in value) || value["signature"] === undefined)
        return false;
    return true;
}

export function DeviceSignatureFromJSON(json: any): DeviceSignature {
    return DeviceSignatureFromJSONTyped(json, false);
}

export function DeviceSignatureFromJSONTyped(
    json: any,
    ignoreDiscriminator: boolean,
): DeviceSignature {
    if (json == null) {
        return json;
    }
    return {
        signature: json["signature"],
    };
}

export function DeviceSignatureToJSON(json: any): DeviceSignature {
    return DeviceSignatureToJSONTyped(json, false);
}

export function DeviceSignatureToJSONTyped(
    value?: DeviceSignature | null,
    ignoreDiscriminator: boolean = false,
): any {
    if (value == null) {
        return value;
    }

    return {
        signature: value["signature"],
    };
}
