/* tslint:disable */
/* eslint-disable */
/**
 * OAuth Server
 * OIDC / OAuth 2.x server implementation
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../runtime.js";
/**
 *
 * @export
 * @interface DevicePairingInvitation
 */
export interface DevicePairingInvitation {
    /**
     *
     */
    expiresAt: number;
    /**
     *
     */
    id: number;
    /**
     *
     */
    secret: string;
}

/**
 * Check if a given object implements the DevicePairingInvitation interface.
 */
export function instanceOfDevicePairingInvitation(
    value: object,
): value is DevicePairingInvitation {
    if (!("expiresAt" in value) || value["expiresAt"] === undefined)
        return false;
    if (!("id" in value) || value["id"] === undefined) return false;
    if (!("secret" in value) || value["secret"] === undefined) return false;
    return true;
}

export function DevicePairingInvitationFromJSON(
    json: any,
): DevicePairingInvitation {
    return DevicePairingInvitationFromJSONTyped(json, false);
}

export function DevicePairingInvitationFromJSONTyped(
    json: any,
    ignoreDiscriminator: boolean,
): DevicePairingInvitation {
    if (json == null) {
        return json;
    }
    return {
        expiresAt: json["expiresAt"],
        id: json["id"],
        secret: json["secret"],
    };
}

export function DevicePairingInvitationToJSON(
    json: any,
): DevicePairingInvitation {
    return DevicePairingInvitationToJSONTyped(json, false);
}

export function DevicePairingInvitationToJSONTyped(
    value?: DevicePairingInvitation | null,
    ignoreDiscriminator: boolean = false,
): any {
    if (value == null) {
        return value;
    }

    return {
        expiresAt: value["expiresAt"],
        id: value["id"],
        secret: value["secret"],
    };
}
