/* tslint:disable */
/* eslint-disable */
/**
 * OAuth Server
 * OIDC / OAuth 2.x server implementation
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../runtime.js";
/**
 *
 * @export
 * @interface DevicePairingInvitationRequest
 */
export interface DevicePairingInvitationRequest {
    /**
     *
     */
    initiatingPublicKey: string;
}

/**
 * Check if a given object implements the DevicePairingInvitationRequest interface.
 */
export function instanceOfDevicePairingInvitationRequest(
    value: object,
): value is DevicePairingInvitationRequest {
    if (
        !("initiatingPublicKey" in value) ||
        value["initiatingPublicKey"] === undefined
    )
        return false;
    return true;
}

export function DevicePairingInvitationRequestFromJSON(
    json: any,
): DevicePairingInvitationRequest {
    return DevicePairingInvitationRequestFromJSONTyped(json, false);
}

export function DevicePairingInvitationRequestFromJSONTyped(
    json: any,
    ignoreDiscriminator: boolean,
): DevicePairingInvitationRequest {
    if (json == null) {
        return json;
    }
    return {
        initiatingPublicKey: json["initiatingPublicKey"],
    };
}

export function DevicePairingInvitationRequestToJSON(
    json: any,
): DevicePairingInvitationRequest {
    return DevicePairingInvitationRequestToJSONTyped(json, false);
}

export function DevicePairingInvitationRequestToJSONTyped(
    value?: DevicePairingInvitationRequest | null,
    ignoreDiscriminator: boolean = false,
): any {
    if (value == null) {
        return value;
    }

    return {
        initiatingPublicKey: value["initiatingPublicKey"],
    };
}
