/* tslint:disable */
/* eslint-disable */
/**
 * OAuth Server
 * OIDC / OAuth 2.x server implementation
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../runtime.js";
/**
 *
 * @export
 * @interface DevicePairingApprovalRequest
 */
export interface DevicePairingApprovalRequest {
    /**
     *
     */
    signature: string;
}

/**
 * Check if a given object implements the DevicePairingApprovalRequest interface.
 */
export function instanceOfDevicePairingApprovalRequest(
    value: object,
): value is DevicePairingApprovalRequest {
    if (!("signature" in value) || value["signature"] === undefined)
        return false;
    return true;
}

export function DevicePairingApprovalRequestFromJSON(
    json: any,
): DevicePairingApprovalRequest {
    return DevicePairingApprovalRequestFromJSONTyped(json, false);
}

export function DevicePairingApprovalRequestFromJSONTyped(
    json: any,
    ignoreDiscriminator: boolean,
): DevicePairingApprovalRequest {
    if (json == null) {
        return json;
    }
    return {
        signature: json["signature"],
    };
}

export function DevicePairingApprovalRequestToJSON(
    json: any,
): DevicePairingApprovalRequest {
    return DevicePairingApprovalRequestToJSONTyped(json, false);
}

export function DevicePairingApprovalRequestToJSONTyped(
    value?: DevicePairingApprovalRequest | null,
    ignoreDiscriminator: boolean = false,
): any {
    if (value == null) {
        return value;
    }

    return {
        signature: value["signature"],
    };
}
