/* tslint:disable */
/* eslint-disable */
/**
 * OAuth Server
 * OIDC / OAuth 2.x server implementation
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../runtime.js";
/**
 *
 * @export
 * @interface Device
 */
export interface Device {
    /**
     *
     */
    address: string;
    /**
     *
     */
    publicKey: string;
}

/**
 * Check if a given object implements the Device interface.
 */
export function instanceOfDevice(value: object): value is Device {
    if (!("address" in value) || value["address"] === undefined) return false;
    if (!("publicKey" in value) || value["publicKey"] === undefined)
        return false;
    return true;
}

export function DeviceFromJSON(json: any): Device {
    return DeviceFromJSONTyped(json, false);
}

export function DeviceFromJSONTyped(
    json: any,
    ignoreDiscriminator: boolean,
): Device {
    if (json == null) {
        return json;
    }
    return {
        address: json["address"],
        publicKey: json["publicKey"],
    };
}

export function DeviceToJSON(json: any): Device {
    return DeviceToJSONTyped(json, false);
}

export function DeviceToJSONTyped(
    value?: Device | null,
    ignoreDiscriminator: boolean = false,
): any {
    if (value == null) {
        return value;
    }

    return {
        address: value["address"],
        publicKey: value["publicKey"],
    };
}
