/* tslint:disable */
/* eslint-disable */
/**
 * OAuth Server
 * OIDC / OAuth 2.x server implementation
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../runtime.js";
/**
 *
 * @export
 * @interface DevicePairingRedemptionRequest
 */
export interface DevicePairingRedemptionRequest {
    /**
     *
     */
    address: string;
    /**
     *
     */
    name: string;
    /**
     *
     */
    publicKey: string;
    /**
     *
     */
    secret: string;
}

/**
 * Check if a given object implements the DevicePairingRedemptionRequest interface.
 */
export function instanceOfDevicePairingRedemptionRequest(
    value: object,
): value is DevicePairingRedemptionRequest {
    if (!("address" in value) || value["address"] === undefined) return false;
    if (!("name" in value) || value["name"] === undefined) return false;
    if (!("publicKey" in value) || value["publicKey"] === undefined)
        return false;
    if (!("secret" in value) || value["secret"] === undefined) return false;
    return true;
}

export function DevicePairingRedemptionRequestFromJSON(
    json: any,
): DevicePairingRedemptionRequest {
    return DevicePairingRedemptionRequestFromJSONTyped(json, false);
}

export function DevicePairingRedemptionRequestFromJSONTyped(
    json: any,
    ignoreDiscriminator: boolean,
): DevicePairingRedemptionRequest {
    if (json == null) {
        return json;
    }
    return {
        address: json["address"],
        name: json["name"],
        publicKey: json["publicKey"],
        secret: json["secret"],
    };
}

export function DevicePairingRedemptionRequestToJSON(
    json: any,
): DevicePairingRedemptionRequest {
    return DevicePairingRedemptionRequestToJSONTyped(json, false);
}

export function DevicePairingRedemptionRequestToJSONTyped(
    value?: DevicePairingRedemptionRequest | null,
    ignoreDiscriminator: boolean = false,
): any {
    if (value == null) {
        return value;
    }

    return {
        address: value["address"],
        name: value["name"],
        publicKey: value["publicKey"],
        secret: value["secret"],
    };
}
