/* tslint:disable */
/* eslint-disable */
/**
 * OAuth Server
 * OIDC / OAuth 2.x server implementation
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../runtime.js";
/**
 *
 * @export
 * @interface PairingAcceptance
 */
export interface PairingAcceptance {
    /**
     *
     */
    accepting: boolean;
}

/**
 * Check if a given object implements the PairingAcceptance interface.
 */
export function instanceOfPairingAcceptance(
    value: object,
): value is PairingAcceptance {
    if (!("accepting" in value) || value["accepting"] === undefined)
        return false;
    return true;
}

export function PairingAcceptanceFromJSON(json: any): PairingAcceptance {
    return PairingAcceptanceFromJSONTyped(json, false);
}

export function PairingAcceptanceFromJSONTyped(
    json: any,
    ignoreDiscriminator: boolean,
): PairingAcceptance {
    if (json == null) {
        return json;
    }
    return {
        accepting: json["accepting"],
    };
}

export function PairingAcceptanceToJSON(json: any): PairingAcceptance {
    return PairingAcceptanceToJSONTyped(json, false);
}

export function PairingAcceptanceToJSONTyped(
    value?: PairingAcceptance | null,
    ignoreDiscriminator: boolean = false,
): any {
    if (value == null) {
        return value;
    }

    return {
        accepting: value["accepting"],
    };
}
