/* tslint:disable */
/* eslint-disable */
/**
 * OAuth Server
 * OIDC / OAuth 2.x server implementation
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../runtime.js";
/**
 *
 * @export
 * @interface SignDeviceMessage
 */
export interface SignDeviceMessage {
    /**
     *
     */
    message: string;
}

/**
 * Check if a given object implements the SignDeviceMessage interface.
 */
export function instanceOfSignDeviceMessage(
    value: object,
): value is SignDeviceMessage {
    if (!("message" in value) || value["message"] === undefined) return false;
    return true;
}

export function SignDeviceMessageFromJSON(json: any): SignDeviceMessage {
    return SignDeviceMessageFromJSONTyped(json, false);
}

export function SignDeviceMessageFromJSONTyped(
    json: any,
    ignoreDiscriminator: boolean,
): SignDeviceMessage {
    if (json == null) {
        return json;
    }
    return {
        message: json["message"],
    };
}

export function SignDeviceMessageToJSON(json: any): SignDeviceMessage {
    return SignDeviceMessageToJSONTyped(json, false);
}

export function SignDeviceMessageToJSONTyped(
    value?: SignDeviceMessage | null,
    ignoreDiscriminator: boolean = false,
): any {
    if (value == null) {
        return value;
    }

    return {
        message: value["message"],
    };
}
