/* tslint:disable */
/* eslint-disable */
/**
 * OAuth Server
 * OIDC / OAuth 2.x server implementation
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../runtime.js";
/**
 *
 * @export
 * @interface StorageSession
 */
export interface StorageSession {
    /**
     *
     */
    applicationId: number;
    /**
     *
     */
    expiresAt: number;
    /**
     *
     */
    token: string;
}

/**
 * Check if a given object implements the StorageSession interface.
 */
export function instanceOfStorageSession(
    value: object,
): value is StorageSession {
    if (!("applicationId" in value) || value["applicationId"] === undefined)
        return false;
    if (!("expiresAt" in value) || value["expiresAt"] === undefined)
        return false;
    if (!("token" in value) || value["token"] === undefined) return false;
    return true;
}

export function StorageSessionFromJSON(json: any): StorageSession {
    return StorageSessionFromJSONTyped(json, false);
}

export function StorageSessionFromJSONTyped(
    json: any,
    ignoreDiscriminator: boolean,
): StorageSession {
    if (json == null) {
        return json;
    }
    return {
        applicationId: json["applicationId"],
        expiresAt: json["expiresAt"],
        token: json["token"],
    };
}

export function StorageSessionToJSON(json: any): StorageSession {
    return StorageSessionToJSONTyped(json, false);
}

export function StorageSessionToJSONTyped(
    value?: StorageSession | null,
    ignoreDiscriminator: boolean = false,
): any {
    if (value == null) {
        return value;
    }

    return {
        applicationId: value["applicationId"],
        expiresAt: value["expiresAt"],
        token: value["token"],
    };
}
