/* tslint:disable */
/* eslint-disable */
/**
 * OAuth Server
 * OIDC / OAuth 2.x server implementation
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../runtime.js";
/**
 *
 * @export
 * @interface TunnelAuthorization
 */
export interface TunnelAuthorization {
    /**
     *
     */
    expiresAt: number;
    /**
     *
     */
    token: string;
}

/**
 * Check if a given object implements the TunnelAuthorization interface.
 */
export function instanceOfTunnelAuthorization(
    value: object,
): value is TunnelAuthorization {
    if (!("expiresAt" in value) || value["expiresAt"] === undefined)
        return false;
    if (!("token" in value) || value["token"] === undefined) return false;
    return true;
}

export function TunnelAuthorizationFromJSON(json: any): TunnelAuthorization {
    return TunnelAuthorizationFromJSONTyped(json, false);
}

export function TunnelAuthorizationFromJSONTyped(
    json: any,
    ignoreDiscriminator: boolean,
): TunnelAuthorization {
    if (json == null) {
        return json;
    }
    return {
        expiresAt: json["expiresAt"],
        token: json["token"],
    };
}

export function TunnelAuthorizationToJSON(json: any): TunnelAuthorization {
    return TunnelAuthorizationToJSONTyped(json, false);
}

export function TunnelAuthorizationToJSONTyped(
    value?: TunnelAuthorization | null,
    ignoreDiscriminator: boolean = false,
): any {
    if (value == null) {
        return value;
    }

    return {
        expiresAt: value["expiresAt"],
        token: value["token"],
    };
}
