/* tslint:disable */
/* eslint-disable */
/**
 * OAuth Server
 * OIDC / OAuth 2.x server implementation
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../runtime.js";
/**
 *
 * @export
 * @interface UpdateDeviceRequest
 */
export interface UpdateDeviceRequest {
    /**
     *
     */
    name: string;
}

/**
 * Check if a given object implements the UpdateDeviceRequest interface.
 */
export function instanceOfUpdateDeviceRequest(
    value: object,
): value is UpdateDeviceRequest {
    if (!("name" in value) || value["name"] === undefined) return false;
    return true;
}

export function UpdateDeviceRequestFromJSON(json: any): UpdateDeviceRequest {
    return UpdateDeviceRequestFromJSONTyped(json, false);
}

export function UpdateDeviceRequestFromJSONTyped(
    json: any,
    ignoreDiscriminator: boolean,
): UpdateDeviceRequest {
    if (json == null) {
        return json;
    }
    return {
        name: json["name"],
    };
}

export function UpdateDeviceRequestToJSON(json: any): UpdateDeviceRequest {
    return UpdateDeviceRequestToJSONTyped(json, false);
}

export function UpdateDeviceRequestToJSONTyped(
    value?: UpdateDeviceRequest | null,
    ignoreDiscriminator: boolean = false,
): any {
    if (value == null) {
        return value;
    }

    return {
        name: value["name"],
    };
}
