/* tslint:disable */
/* eslint-disable */
/**
 * OAuth Server
 * OIDC / OAuth 2.x server implementation
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import {
    mapValues,
    parseDate,
    parseDateTime,
    serializeDate,
    serializeDateTime,
} from "../runtime.js";
/**
 *
 * @export
 * @interface UserInfo
 */
export interface UserInfo {
    /**
     *
     */
    birthdate?: string | null;
    /**
     *
     */
    email?: string | null;
    /**
     *
     */
    emailVerified?: boolean | null;
    /**
     *
     */
    familyName?: string | null;
    /**
     *
     */
    gender?: string | null;
    /**
     *
     */
    givenName?: string | null;
    /**
     *
     */
    locale?: string | null;
    /**
     *
     */
    middleName?: string | null;
    /**
     *
     */
    name?: string | null;
    /**
     *
     */
    nickname?: string | null;
    /**
     *
     */
    permissions?: Array<string>;
    /**
     *
     */
    phoneNumber?: string | null;
    /**
     *
     */
    phoneNumberVerified?: boolean | null;
    /**
     *
     */
    picture?: string | null;
    /**
     *
     */
    preferredUsername?: string | null;
    /**
     *
     */
    profile?: string | null;
    /**
     *
     */
    sub: string;
    /**
     *
     */
    updatedAt: Date;
    /**
     *
     */
    website?: string | null;
    /**
     *
     */
    zoneinfo?: string | null;
}

/**
 * Check if a given object implements the UserInfo interface.
 */
export function instanceOfUserInfo(value: object): value is UserInfo {
    if (!("sub" in value) || value["sub"] === undefined) return false;
    if (
        (!("updatedAt" in (value as Record<string, any>)) &&
            !("updated_at" in (value as Record<string, any>))) ||
        ((value as Record<string, any>)["updatedAt"] === undefined &&
            (value as Record<string, any>)["updated_at"] === undefined)
    )
        return false;
    return true;
}

export function UserInfoFromJSON(json: any): UserInfo {
    return UserInfoFromJSONTyped(json, false);
}

export function UserInfoFromJSONTyped(
    json: any,
    ignoreDiscriminator: boolean,
): UserInfo {
    if (json == null) {
        return json;
    }
    return {
        birthdate:
            json["birthdate"] === undefined
                ? undefined
                : json["birthdate"] === null
                  ? null
                  : json["birthdate"],
        email:
            json["email"] === undefined
                ? undefined
                : json["email"] === null
                  ? null
                  : json["email"],
        emailVerified:
            json["email_verified"] === undefined
                ? undefined
                : json["email_verified"] === null
                  ? null
                  : json["email_verified"],
        familyName:
            json["family_name"] === undefined
                ? undefined
                : json["family_name"] === null
                  ? null
                  : json["family_name"],
        gender:
            json["gender"] === undefined
                ? undefined
                : json["gender"] === null
                  ? null
                  : json["gender"],
        givenName:
            json["given_name"] === undefined
                ? undefined
                : json["given_name"] === null
                  ? null
                  : json["given_name"],
        locale:
            json["locale"] === undefined
                ? undefined
                : json["locale"] === null
                  ? null
                  : json["locale"],
        middleName:
            json["middle_name"] === undefined
                ? undefined
                : json["middle_name"] === null
                  ? null
                  : json["middle_name"],
        name:
            json["name"] === undefined
                ? undefined
                : json["name"] === null
                  ? null
                  : json["name"],
        nickname:
            json["nickname"] === undefined
                ? undefined
                : json["nickname"] === null
                  ? null
                  : json["nickname"],
        permissions:
            json["permissions"] == null ? undefined : json["permissions"],
        phoneNumber:
            json["phone_number"] === undefined
                ? undefined
                : json["phone_number"] === null
                  ? null
                  : json["phone_number"],
        phoneNumberVerified:
            json["phone_number_verified"] === undefined
                ? undefined
                : json["phone_number_verified"] === null
                  ? null
                  : json["phone_number_verified"],
        picture:
            json["picture"] === undefined
                ? undefined
                : json["picture"] === null
                  ? null
                  : json["picture"],
        preferredUsername:
            json["preferred_username"] === undefined
                ? undefined
                : json["preferred_username"] === null
                  ? null
                  : json["preferred_username"],
        profile:
            json["profile"] === undefined
                ? undefined
                : json["profile"] === null
                  ? null
                  : json["profile"],
        sub: json["sub"],
        updatedAt:
            json["updated_at"] == null
                ? json["updated_at"]
                : parseDateTime(json["updated_at"]),
        website:
            json["website"] === undefined
                ? undefined
                : json["website"] === null
                  ? null
                  : json["website"],
        zoneinfo:
            json["zoneinfo"] === undefined
                ? undefined
                : json["zoneinfo"] === null
                  ? null
                  : json["zoneinfo"],
    };
}

export function UserInfoToJSON(json: any): UserInfo {
    return UserInfoToJSONTyped(json, false);
}

export function UserInfoToJSONTyped(
    value?: UserInfo | null,
    ignoreDiscriminator: boolean = false,
): any {
    if (value == null) {
        return value;
    }

    return {
        birthdate: value["birthdate"],
        email: value["email"],
        email_verified: value["emailVerified"],
        family_name: value["familyName"],
        gender: value["gender"],
        given_name: value["givenName"],
        locale: value["locale"],
        middle_name: value["middleName"],
        name: value["name"],
        nickname: value["nickname"],
        permissions: value["permissions"],
        phone_number: value["phoneNumber"],
        phone_number_verified: value["phoneNumberVerified"],
        picture: value["picture"],
        preferred_username: value["preferredUsername"],
        profile: value["profile"],
        sub: value["sub"],
        updated_at:
            value["updatedAt"] == null
                ? value["updatedAt"]
                : serializeDateTime(value["updatedAt"]),
        website: value["website"],
        zoneinfo: value["zoneinfo"],
    };
}
