/* tslint:disable */
/* eslint-disable */
/**
 * OAuth Server
 * OIDC / OAuth 2.x server implementation
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 */
export const UserDeviceState = {
    Pending: "pending",
    Approved: "approved",
    Revoked: "revoked",
} as const;
export type UserDeviceState =
    (typeof UserDeviceState)[keyof typeof UserDeviceState];

export function instanceOfUserDeviceState(value: any): boolean {
    for (const key in UserDeviceState) {
        if (Object.prototype.hasOwnProperty.call(UserDeviceState, key)) {
            if (
                UserDeviceState[key as keyof typeof UserDeviceState] === value
            ) {
                return true;
            }
        }
    }
    return false;
}

export function UserDeviceStateFromJSON(json: any): UserDeviceState {
    return UserDeviceStateFromJSONTyped(json, false);
}

export function UserDeviceStateFromJSONTyped(
    json: any,
    ignoreDiscriminator: boolean,
): UserDeviceState {
    return json as UserDeviceState;
}

export function UserDeviceStateToJSON(value?: UserDeviceState | null): any {
    return value as any;
}

export function UserDeviceStateToJSONTyped(
    value: any,
    ignoreDiscriminator: boolean,
): UserDeviceState {
    return value as UserDeviceState;
}
